config/routes.rb
Rails.application.routes.draw do
  get '/' => 'sessions#index'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  delete '/logout' => 'sessions#destroy'
  #don't need a post signup because resources has it covered, and users don't see the URL

  get '/auth/:provider/callback' => 'sessions#google'
  #directs any auth callback response to sessions control google action
 
  resources :comments
  resources :jobs
  resources :jobs do
    # nested resource for jobs
    resources :comments, only: [:new, :index]
  end

  resources :companies
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :job

  validates :content, presence: true

end

app/models/company.rb
class Company < ApplicationRecord
    has_many :jobs

    validates :name, uniqueness: true

    scope :alpha, -> { order(:name) }
    
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
  belongs_to :company
  has_many :comments
  has_many :users, through: :comments
  accepts_nested_attributes_for :company, reject_if: proc { |attributes| attributes['name'].blank? }
  # accepts_nested_attributes_for :comment

  validates :title, presence: true

  scope :alpha, -> { order(:title) }


end

app/models/user.rb
class User < ApplicationRecord
    has_many :comments
    has_many :commented_jobs, through: :comments, source: :job   
    #"job" above matches belongs_to :job in comments model
    has_many :jobs #that are created by user

    validates :username, uniqueness: true,  presence: true
    validates :email, presence: true

    has_secure_password

    def self.from_omniauth(response)
        User.find_or_create_by(uid: response[:uid], provider: response[:provider]) do |user|
        user.username = response[:info][:name]
        user.email = response[:info][:email]
        user.password = SecureRandom.hex(15)
        end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :logged_in?, :current_user
  
  private
  
    def logged_in?
        !!current_user
    end
      
    def current_user  
        @current_user ||= User.find(session[:user_id]) if session[:user_id] 
        #if current user is already defined, it will equal #current user
        #otherwise it will find user id in the user table
    end
  
    def redirect_if_not_logged_in
        if !logged_in?
            redirect_to '/'
        end
    end 

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :redirect_if_not_logged_in

    def new
        if @job = Job.find_by_id(params[:job_id]) 
            @comment = @job.comments.build
            #use build so the comment already knows which job is assoc
          else
            @comment = Comment.new
          end
    end

    def create
      @comment = Comment.new(comment_params)
      @comment.user_id = session[:user_id] 
      # @comment = current_user.comments.build(comment_params)
      #if it reloads, we want it to re-render the information that has been added so far
      if @comment.save
          #retuns same value as valid. automatically checks belongs to
          redirect_to comment_path(@comment)
      else           
          render :new
      end
    end

    def index
      if params[:job_id]
          @comments = Job.find(params[:job_id]).comments
      else
        @comments = Comment.all
      end 
    end

    def show
      @comment = Comment.find_by_id(params[:id])
    end

  def comment_params
      params.require(:comment).permit(:content, :job_id)
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
    before_action :redirect_if_not_logged_in
    
    def index
        @companies = Company.all
        @companies = Company.alpha
    end

    def show
        @company = Company.find_by_id(params[:id])
    end

    private

    def company_params
        params.require(:company).permit(:name, :location)
    end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
    before_action :redirect_if_not_logged_in
    before_action :set_job, only: [:edit, :udpate]
    
    def index
        @jobs = Job.all
        @jobs = Job.alpha
    end

    def new
       @job = Job.new 
       @job.build_company 
       #put build in new because we're not doing it in edit
    end

    def create
        @job = Job.new(job_params)
        @job.user_id = session[:user_id] 
        #if it reloads, we want it to re-render the information that has been added so far
        if @job.save
            #retuns same value as valid
            redirect_to job_path(@job)
        else           
            render :new
        end
    end

    def show
        if set_job
        else 
            redirect_to '/'
        end 
    end

    def edit
    end

    def update
        @job.update(job_params)
        redirect_to job_path(@job)
    end
     
    private

    def job_params
        params.require(:job).permit(:title, :level, :link, :company_id, company_attributes: [:name, :location])
        #company_attributes comes from accepts_nested_attributes in model
    end

    def set_job
        @job = Job.find_by_id(params[:id])
    end
 

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def index
    end

    def new
        @user = User.new
    end

    def create
        @user = User.find_by(username: params[:user][:username])
        #did we find the user and did they enter the correct password?
        if @user && @user.authenticate(params[:user][:password])
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            flash[:alert] = "Please try again. Your login details are incorrect."
            redirect_to login_path
        end
    end

    def google
        user = User.from_omniauth(request.env['omniauth.auth'])
            if user.valid?
                session[:user_id] = user.id
                redirect_to user_path(user)
            else
                redirect_to '/login'
            end
    end
    
    def destroy
        session.delete(:user_id)
        redirect_to '/'
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        #if it reloads, we want it to re-render the information that has been added so far
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else           
            render :new 
        end
    end

    def show
        @user = User.find_by_id(params[:id])
        redirect_to '/' if !@user
    end

    private

    def user_params
        params.require(:user).permit(:first_name, :last_name, :grad_date, :linkedin_profile, :status, :username, :email, :password)
    end
end
 

app/views/comments/_comment_nav.html.erb
<br>
<br>
<%= link_to "Go Back to Job Details", job_path(@job) %>

<%= render 'layouts/nav_logged_in' %>

app/views/comments/index.html.erb
<h1> Comments </h1>


<% @comments.each do |comment| %>
<li><%= link_to comment.content, comment_path(comment)%></li>
<% end %>


<%= render 'layouts/nav_logged_in' %>

app/views/comments/new.html.erb
<h1> Add a Comment about <%= @comment.job.title %> - <%= @comment.job.company.name %> </h1>

<%= render partial: "layouts/errors", locals: {obj: @comment} %>

<%= form_for(@comment) do |f| %>

  <%= f.label :content %>
  <%= f.text_area :content %>
  <br>
  <br>
  <%= f.hidden_field :job_id %>
  <br>
  <br>
  <%= f.submit "Add a Comment" %>



<% end %>

<%= render 'comment_nav' %>

app/views/comments/show.html.erb
<h1> Comment submitted by: <%= @comment.user.first_name %> </h1>

<%= @comment.content %>

<%= render 'layouts/nav_logged_in' %>

app/views/companies/index.html.erb
<h1> Company List </h1>

<% @companies.each do |company| %> 
<%= link_to company.name, company_path(company.id) %> - <%= company.jobs.size %> jobs posted </h3>
<br>
<% end %>

<%= render 'layouts/nav_logged_in' %>

app/views/companies/show.html.erb
<h1> Company Details</h1>

<h2>Here are more details about the company you selected. </h2>
<br>
<h3>Name: <%= @company.name %> </h3>
<h3>Location: <%= @company.location %> </h3>


<%= render 'layouts/nav_logged_in' %>

app/views/jobs/_form.html.erb
<%= render partial: "layouts/errors", locals: {obj: @job} %>

<%= form_for(@job) do |f| %>

 <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <br>
  <%= f.label :level %>
  <%= f.text_field :level %>
  <br>
  <br>
  <%= f.label :link %>
  <%= f.url_field :link %>
  <br>
  <br>

    <p> Select a company from the list, or skip to the next section to add a new company. </p>
  <div>
  <%= f.collection_select :company_id, Company.all, :id, :name, prompt: true %>
   <br>
  <br>
    <div>

    <p> If you do not see the company on the dropdown list above, add a new company here. </p>
  <div>
  <%= f.fields_for :company do |c| %>
    <%= c.label :name %>
    <%= c.text_field :name, value: nil %>
    <br>
    <br>
    <%= c.label :location %>
    <%= c.text_field :location %>
    <br>
    <br>
<% end %>

<%= f.submit "Submit" %>

<% end %>

<%= render 'layouts/nav_logged_in' %>

app/views/jobs/edit.html.erb
<h1> Edit a Job </h1>

<%= render partial: "form" %>

app/views/jobs/index.html.erb
<h1> Jobs List </h1>
<h2> Click on a job below to see more details and comment on the job. </h2>

<% @jobs.each do |job| %> 
<%= link_to job.title, job_path(job.id) %> - <%= job.company.name %> 

<br>

<% end %>

<%= render 'layouts/nav_logged_in' %>

app/views/jobs/new.html.erb
<h1> Add a Job </h1>

<%= render partial: "form" %>

app/views/jobs/show.html.erb
<h1> Job Details </h1>


<h2>Here are more details about the job you selected. </h2>
<br>
<h3>Company: <%= @job.company.name%></h3>
<h3>Title: <%= @job.title %> </h3>
<h3>Level: <%= @job.level %> </h3>
<h3>Link: <%= @job.link %> </h3>
<h3>Added Date: <%= @job.created_at %> </h3>
<h3>Added By: <%= @job.user.first_name %> <%= @job.user.last_name %> </h3>

<%= link_to "Edit Job Details", edit_job_path %> |
<%= link_to "See Comments", job_comments_path(@job) %> |
<%= link_to "Add a Comment", new_job_comment_path(@job) %> 

<%= render 'layouts/nav_logged_in' %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(obj.errors.count, "error") %> prohibited this from being saved:</h2>
 
    <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_nav_logged_in.html.erb
  <h2>Main Menu</h2>
    <%= link_to "See Job List", jobs_path%>
    <br>
    <br>
    <%= link_to "Add a Job", new_job_path%>
    <br>
    <br> 
    <%= link_to "See Company List", companies_path%>
    <br>
    <br>
    <%= link_to "Log Out", logout_path, method: :delete%>
    <br>
    <br>
  <i>You are logged in with the following email:  <%= current_user.email %><i>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlatironJobResource</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
    <%= yield %>
  </body>

</html>

app/views/users/new.html.erb
<h1>Sign Up Page</h1>
<h2>Please enter your information below to sign up.</h2>

<%= render partial: "layouts/errors", locals: {obj: @user} %>

<%= form_for(@user) do |f| %>
  
  <%= f.label :username %>
  <%= f.text_field :username %>
  <br>
  <br>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <br>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>
  <br>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <br>
  <br>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <br>
  <br>
  <%= f.label :LinkedIn_profile %>
  <%= f.text_field :linkedin_profile %>
  <br>
  <br>
  <%= f.label :grad_date %>
  <%= f.text_field :grad_date %>
  <br>
  <br>
  <%= f.label :status %>
  <%= f.text_field :status %>
  <br>
  <br>
  <%= f.submit "Sign Up" %>
<% end %>

app/views/users/show.html.erb
<h1> Hello <%= @user.first_name %>, you are signed in. </h1>

<%= render partial: "layouts/nav_logged_in" %>